# Extracting unique data

In [1]:
import pandas as pd
import numpy as np

In [6]:
raw_data = pd.read_excel('data/240323_consolidation_dataset_template_flow-deposit_WP3_version3_SLASH_v3.xlsx', sheet_name='template_flow-depositNEW', header=8)

In [7]:
raw_data=raw_data[['uniqueStockOrFlowName','processSpecification','processSpecificationDetailed','LoWkey','descriptionFromDataSource']]

In [10]:
raw_data.drop_duplicates(inplace=True)

In [12]:
raw_data.reset_index(drop=True, inplace=True)

In [13]:
raw_data.to_excel('data/WP3codes.xlsx')

# Check if unique anmes are correct

In [9]:
wp3_data = pd.read_excel('data/WP3codemapping.xlsx', header =1)

In [10]:
wp3_check = pd.read_excel('data/unique_names_WP3.xlsx')

In [6]:
wp3_data

,uniqueStockOrFlowName,processSpecification,processSpecificationDetailed,LoWkey,descriptionFromDataSource,LoWkey.1
0,SLASH_slagsMetallurgical,Pyrometallurgical process,Electric arc furnace (EAF),10 02 02_EAF,EAF slag,NaN
1,SLASH_slagsMetallurgical,Pyrometallurgical process,Basic oxygen furnace (BOF),10 02 02_BOF,BOF Slag,NaN
2,SLASH_slagsMetallurgical,Pyrometallurgical process,Basic oxygen furnace (BOF),10 02 02,slag from BOF,NaN
3,SLASH_slagsMetallurgical,Pyrometallurgical process,NaN,10 02 02,slagheap,NaN
4,SLASH_slagsMetallurgical,Pyrometallurgical process,Blast furnace,10 02 02_BF,Ground granulated blast furn/ace slag,NaN
...,...,...,...,...,...,...
346,SLASH_ashesEnergyProductionGenerated,NaN,NaN,10 01 03,eucalyptus bark ash,10 01 03
347,SLASH_ashesEnergyProductionGenerated,FBC-fluidized bed combustion,Lab scale,10 01 03,straw ash,10 01 03
348,SLASH_ashesEnergyProductionGenerated,FBC-fluidized bed combustion,NaN,10 01 17,rice husk fly ash,10 01 17_A
349,SLASH_ashesEnergyProductionGenerated,FBC-fluidized bed combustion,NaN,10 01 15,rice husk bottom ash,10 01 15_A
350,SLASH_bottomAshesWasteInc,Incineration,NaN,19 01 11*,Bottom ash and slag containing dangerous subst...,19 01 11*

In [11]:
wp3_check

                           descriptionFrom DataSource
0                       meat and bone meal bottom ash
1   bottom ash directly from the exit of the water...
2                                  chicken litter ash
3                              Meat and bone meal ash
4                            poultry manure mixed ash
5        bottom ash or bed ash (26% of the total ash)
6   boiler ash or SH ash (6% of the total ash), co...
7   bottom ash of Rice husk poultry litter ash (RH...
8                                  poultry litter ash
9                                  chickens' bone ash
10                                ash from cow manure
11                            ash from chicken litter
12                     municipal and industrial waste
13                      meat bone and meal bottom ash
14                              Sewage sludge fly ash
15                                      straw fly ash
16                             meat bone and meal ash
17                                 Animal carcass ash
18                        ash from meat bone and meal
19                                   paper sludge ash
20                                       wood fly ash
21                            grapes waste bottom ash
22                    bottom ash from incinerating of
23  bottom ash from incinerating of 33% olive tree...
24                            Agricultural bottom ash
25               almond husk and alpeorujo bottom ash
26                                  boiler bottom ash
27                         exhausted olive cake ashes
28                                 almond shell ashes
29                           almond-shell biomass ash
30                            Olive-stone biomass ash
31                                      rice husk ash
32                   wood and agricultural bottom ash
33                                 Dry olive cake ash
34  Olive cake and agricultural and forest biomass...
35                                     corn straw ash
36                                     rape straw ash
37                                   Palm kernels ash
38                                 olive residues ash
39                                   pepper plant ash
40                                   Energy Crops ash
41                                   Agricultural ash
42                      agri-food industry wastes ash
43                                        feather ash
44                              ash from cereal straw
45                                   Olive kernel ash
46                                 cotton residue ash
47                                   switch grass ash
48                           sunflower seed shell ash
49          80% wood pellets and 20% straw bottom ash
50                                          Straw ash
51                                     rice straw ash
52                                        bagasse ash
53                                    grape seeds ash
54                                  almond shells ash
55                               rice husk bottom ash
56                            olive kernel bottom ash

In [12]:
wp3_check.isin(wp3_data['descriptionFromDataSource'])

    descriptionFrom DataSource
0                        False
1                        False
2                        False
3                        False
4                        False
5                        False
6                        False
7                        False
8                        False
9                        False
10                       False
11                       False
12                       False
13                       False
14                       False
15                       False
16                       False
17                       False
18                       False
19                       False
20                       False
21                       False
22                       False
23                       False
24                       False
25                       False
26                       False
27                       False
28                       False
29                       False
30                       False
31                       False
32                       False
33                       False
34                       False
35                       False
36                       False
37                       False
38                       False
39                       False
40                       False
41                       False
42                       False
43                       False
44                       False
45                       False
46                       False
47                       False
48                       False
49                       False
50                       False
51                       False
52                       False
53                       False
54                       False
55                       False
56                       False